[package]
name = "control_flow_3_5"
version = "0.1.0"
authors = ["mefool <vicentegarciafernandes@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
